- platform: rest
  name: Garage Status
  resource: !secret cgd_api_status_url
  method: GET
  value_template: "{{ value_json.door }}"
  scan_interval: 10   # check every 10 seconds
  json_attributes:
    - dt
    - error
    - camera
- platform: file
  name: Git Backup Status
  file_path: /config/git_backup_status.json
  value_template: "{{ value_json.status }}"
  json_attributes:
    - last_run
    - last_success
    - message